server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = /sw-download.js {
        alias /usr/share/nginx/html/app/sw-download.js;
    }

    location /app/ {
        try_files $uri $uri/ /app/index.html;
    }

    location = / {
        return 301 $scheme://$http_host/app/;
    }
}
